In [ ]:
import numpy as np


In [ ]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'a

In [ ]:
dir(list)



['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [ ]:
help(list)

Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |
 |  Built-in mutable sequence.
 |
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, index, /)
 |      Return self[index].
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate sign

In [ ]:
deepika=[[1,2,3,4,5],
        [1,2,3,4,5]]
print(deepika)

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]


In [ ]:
print(deepika[0][0])

1


In [ ]:
print(deepika[1][-1])

5


In [ ]:
import numpy as np


In [ ]:
var_1 = 'deepika'
dir(np.char)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'add',
 'array',
 'asarray',
 'capitalize',
 'center',
 'chararray',
 'compare_chararrays',
 'count',
 'decode',
 'encode',
 'endswith',
 'equal',
 'expandtabs',
 'find',
 'greater',
 'greater_equal',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'islower',
 'isnumeric',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'less',
 'less_equal',
 'ljust',
 'lower',
 'lstrip',
 'mod',
 'multiply',
 'not_equal',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'str_len',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [ ]:
np.char.upper(var_1)

array('DEEPIKA', dtype='<U7')

In [ ]:
dir(int)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'is_integer',
 

In [ ]:
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'stri

In [ ]:
import numpy as np

In [ ]:
dir(np.char)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'add',
 'array',
 'asarray',
 'capitalize',
 'center',
 'chararray',
 'compare_chararrays',
 'count',
 'decode',
 'encode',
 'endswith',
 'equal',
 'expandtabs',
 'find',
 'greater',
 'greater_equal',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'islower',
 'isnumeric',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'less',
 'less_equal',
 'ljust',
 'lower',
 'lstrip',
 'mod',
 'multiply',
 'not_equal',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'str_len',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'add',
 'array',
 'asarray',
 'capitalize',
 'center',
 'chararray',
 'compare_chararrays',
 'count',
 'decode',
 'encode',
 'endswith',
 'equal',
 'expandtabs',
 'find',
 'greater',
 'greater_equal',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'islower',
 'isnumeric',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'less',
 'less_equal',
 'ljust',
 'lower',
 'lstrip',
 'mod',
 'multiply',
 'not_equal',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'str_len',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [ ]:
var_1 = "Deepika"
np.char.upper(var_1)

array('DEEPIKA', dtype='<U7')

In [ ]:
help(np.char)

Help on package numpy.char in numpy:

NAME
    numpy.char

DESCRIPTION
    This module contains a set of functions for vectorized string
    operations and methods.

    .. note::
       The `chararray` class exists for backwards compatibility with
       Numarray, it is not recommended for new development. Starting from numpy
       1.4, if one needs arrays of strings, it is recommended to use arrays of
       `dtype` `object_`, `bytes_` or `str_`, and use the free functions
       in the `numpy.char` module for fast vectorized string operations.

    Some methods will only be available if the corresponding string method is
    available in your version of Python.

    The preferred alias for `defchararray` is `numpy.char`.

PACKAGE CONTENTS


CLASSES
    numpy.ndarray(builtins.object)
        chararray

    class chararray(numpy.ndarray)
     |  chararray(shape, itemsize=1, unicode=False, buffer=None, offset=0, strides=None, order='C')
     |
     |  chararray(shape, itemsize=1, unic

In [ ]:
var_1="Deepika"
np.char.upper(var_1)

array('DEEPIKA', dtype='<U7')

In [ ]:
print(np.char.upper(var_1))

DEEPIKA


In [ ]:
print(np.char.title(var_1))

Deepika


In [ ]:
print(np.char.swapcase(var_1))

dEEPIKA


In [ ]:
print(np.char.zfill(var_1,10))

000Deepika


In [ ]:
var_1 = "chilakala"
var_2 = "Deepika"

print(np.char.add(var_1,var_2))

chilakalaDeepika


In [ ]:
var_3 = "Reddy"
print(np.char.replace(var_3,"dd","DD"))

ReDDy


In [ ]:
print(np.char.lower(var_3))

reddy


In [ ]:
print(np.char.find(var_3,"R"))

0


In [ ]:
print(np.char.find(var_3,"d"))

2


In [ ]:
print(np.char.join("*",var_3))

R*e*d*d*y


In [ ]:
print(np.char.join("@",var_3))

R@e@d@d@y


In [ ]:
a = "rami reddy deepika reddy"
print(np.char.split(a))

['rami', 'reddy', 'deepika', 'reddy']


In [ ]:
print(np.char.str_len(a))

24


In [ ]:
print(np.char.isdigit(a))

False


In [ ]:
print(np.char.isalpha(a))

False


In [ ]:
print(np.char.isupper(a))

False


In [ ]:
b = "REDDY"
print(np.char.isupper(b))

True


In [ ]:
b = "reddy"
print(np.char.islower(b))

True


In [ ]:
print(np.char.count(a,"d"))

5


In [ ]:
n = "DEEPIKA"
print(np.char.count(n,"E"))

2


In [ ]:
r = "REDDY"
Y = "REDDY"
print(np.char.equal(r,Y))

True


In [ ]:
a = "reddy"
b = "REDDY"
print(np.char.not_equal(a,b))

True


In [ ]:
print(np.char.equal(a,b))

False


In [ ]:
print(np.char.greater(a,b))

True


In [ ]:
print(np.char.less(a,b))

False


In [ ]:
a = "REDDY"
print(np.char.swapcase(a))

reddy


In [ ]:
a = "reddy"
print(np.char.swapcase(a))

REDDY


In [ ]:
print(np.char.center(a,20,"#"))

#######reddy########


In [ ]:
print(np.char.center(a,20,"r"))

rrrrrrrreddyrrrrrrrr


In [ ]:
print(np.char.center(a,20,"+"))

+++++++reddy++++++++


In [ ]:
print(np.char.isalnum(a))

True


In [ ]:
a =    "DEEPIKA"
print(np.char.ljust(a,10,"_"))

DEEPIKA___


In [ ]:
print(np.char.ljust(a,10,"*"))

DEEPIKA***


In [ ]:
print(np.char.strip("    DEEPIKA    "))

DEEPIKA


In [ ]:
a = "reddy"
print(np.char.startswith(a,"R"))

False


In [ ]:
print(np.char.startswith(a,"r"))

True


In [ ]:
print(np.char.rsplit("Budda Bharadwaja Reddy"))

['Budda', 'Bharadwaja', 'Reddy']


In [ ]:
print(np.char.rsplit("Budda Bharadwaja Reddy"))

['Budda', 'Bharadwaja', 'Reddy']


In [ ]:
a = "Budda Bharadwaja Reddy"
print(np.char.count(a, "B"))

2


In [ ]:
print(np.char.partition("Budda Bharadwaja Reddy","_"))

['Budda Bharadwaja Reddy' '' '']


In [ ]:
print(np.char.partition("deepika-reddychilakala","-"))

['deepika' '-' 'reddychilakala']


In [ ]:
print(np.char.partition("abc-def", "-"))

['abc' '-' 'def']


In [ ]:
a = "deepika reddy"
print(np.char.mod( "%s" , a))

deepika reddy


In [ ]:
a = "deepikareddy"
print(np.char.mod( "%s" , a))

deepikareddy


In [ ]:
import numpy as np
array_1D=np.array([1,2,3,4,5])

type(array_1D)

numpy.ndarray

In [ ]:
array_1D.dtype

dtype('int64')

In [ ]:
import numpy as np
array_1D=np.array([1.1,2.2,3,4,5])

type(array_1D)

numpy.ndarray

In [ ]:
array_1D.dtype

dtype('float64')

In [ ]:
import numpy as np
array_11D=np.array([1,2,"char",bool])

print(type(array_11D))


<class 'numpy.ndarray'>


In [ ]:
array_11D.dtype

dtype('O')

In [ ]:
#dimention
print("number of dimentions :",array_11D.ndim)

number of dimentions : 1


In [ ]:
#size
print("size of array:",array_11D.size)

size of array: 4


In [ ]:
#shape
print("shape of an array:",array_11D.shape)

shape of an array: (4,)


In [ ]:
array_2d = np.array([[1,2,3,4,5],[1,2,3,4,5]])
type(array_2d)


numpy.ndarray

In [ ]:
print(array_2d.dtype)
print(array_2d.ndim)
print(array_2d.shape)
print(array_2d.size)

int64
2
(2, 5)
10


In [ ]:
array_3D = np.array([[[1,2],[4,5],[1,2],[2,3]]])
type(array_3D)

numpy.ndarray

In [ ]:
print(array_3D.size)

8


In [ ]:
print(array_3D.ndim)

3


In [ ]:
for row in array_3D:
  print(row)

[[1 2]
 [4 5]
 [1 2]
 [2 3]]


In [ ]:
mx_zeros = np.zeros(2)
print(mx_zeros)

[0. 0.]


In [ ]:
mx_0s = np.zeros(5)
print(mx_0s)

[0. 0. 0. 0. 0.]


In [ ]:
mx_0s_2d = np.zeros([6])
print(mx_0s_2d)
print(mx_0s_2d.ndim)


[0. 0. 0. 0. 0. 0.]
1


In [ ]:
mx_0s_2d = np.zeros([2,4])
print(mx_0s_2d)
print(mx_0s_2d.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2


In [ ]:
array_1D = np.array([1.1,2.2,3.3,4],dtype='int64')
print(array_1D)

[1 2 3 4]


In [ ]:
array_1D = np.array([1,2,3,4],dtype=float)
print(array_1D)

[1. 2. 3. 4.]


In [ ]:
array_2d = np.array([1,2,3,4,5])
print(array_2d.dtype)

int64


In [ ]:
mx_zeros = np.zeros((4,5),dtype='int64')
print(mx_zeros)
print(mx_zeros.ndim)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
2


In [ ]:
mx_ones = np.ones((10,20),dtype='int64')
print(mx_ones)
print(mx_ones.ndim)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
2


In [ ]:
mx_ones = np.ones((4,5),dtype='int64')
print(mx_ones)
print(mx_ones.ndim)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
2


In [ ]:
mx_full= np.full((4,5),5,dtype='int64')
print(mx_full)


[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


**Arrange function**

In [ ]:
ar_2d = np.arange(1,13)
print(ar_2d.reshape(2,6))




[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
np.linspace(1,13,9)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. , 11.5, 13. ])

In [ ]:
array_2d = np.array([[1,2,3,4,5],[1,2,3,4,5]])
type(array_2d)
print(array_2d)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [ ]:
array_2d.ravel()

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [ ]:
array_2d.flatten()

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [ ]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(arr1+arr2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
print(arr1*arr2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
print(arr1/arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(arr1-arr2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.multiply(arr1,arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
np.divide(arr1,arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Broadcasting – Definition
Broadcasting is a NumPy feature that allows arithmetic operations between arrays of different shapes.
It automatically expands the smaller array to match the shape of the larger array.
This expansion is virtual (no actual copying of data), making operations faster and memory-efficient.
Rules of Broadcasting (in Points)
Compare shapes from right to left.
NumPy starts comparing dimensions from the last (rightmost) dimension.
Dimensions must be equal or one of them must be 1.
If the dimensions are the same, broadcasting is possible.
If one dimension is 1, it is stretched to match the other dimension.
Missing dimensions are treated as 1.
If one array has fewer dimensions, NumPy assumes leading dimensions of size 1.
If dimensions are neither equal nor 1, broadcasting fails.
NumPy raises a ValueError.
The output array has the shape of the larger array after broadcasting.

In [ ]:
import numpy as np
arr_1d = np.array([1,2,3,4,5])
a = arr_1d+2
print(a)

[3 4 5 6 7]


In [ ]:
arr_1d = np.array([1,2,3,4,5])
arr_sc = np.array([5])
a = arr_1d * arr_sc
print(a)

[ 5 10 15 20 25]


In [ ]:
arr_1d = np.array([1,2,3,4,5])
a = arr_1d * 5
print(a)

[ 5 10 15 20 25]


In [ ]:
arr_2d = np.array([[1,2,3,4,5],[3,4,5,5,6]])
a = arr_2d*2
print(a)

[[ 2  4  6  8 10]
 [ 6  8 10 10 12]]


In [ ]:
arr_2d = np.array([[1,2,3,4,5],[3,4,5,5,6]])
arr_sc = np.array([5])
a = arr_2d*arr_sc
print(a)

[[ 5 10 15 20 25]
 [15 20 25 25 30]]


In [ ]:
arr_2d = np.array([[1,2,3,4,5],[3,4,5,5,6]])
a = arr_2d*5
print(a)

[[ 5 10 15 20 25]
 [15 20 25 25 30]]


In [ ]:
arr_2d = np.array([[1,2,3,4,5],[3,4,5,5,6]])
arr_1d = np.array([1,2,3,4,5])
a = arr_2d*arr_1d
b= a.flatten()

print(b)

[ 1  4  9 16 25  3  8 15 20 30]


In [ ]:
np.sin(160)

np.float64(0.21942525837900473)

In [ ]:
a = "Deepika"
b = "hello"

np.char.add(a,b)

np.str_('Deepikahello')

In [ ]:
np.char.upper(a)

array('DEEPIKA', dtype='<U7')

In [ ]:
a = np.array([[1],[2],[3]])
b = np.array([10,20,30])
c = a*b
print(c)

[[10 20 30]
 [20 40 60]
 [30 60 90]]


In [ ]:
a = np.array([[1],[2],[3]])
b = np.array([10,20,30])
c = a*b
d = c.flatten()
print(d)

[10 20 30 20 40 60 30 60 90]


In [ ]:
var = np.array([1,2,3,4,5])
print(var)

[1 2 3 4 5]


In [ ]:
var[1]

np.int64(2)

In [ ]:
#MASKING
a = np.array([2,-2,3,-4])
index = [0,1]
a[index]

array([ 2, -2])

In [ ]:
arr = np.array([-1,2,-3,4,-5])
index = [0,2,3]
arr[index]
aws = arr[arr>0]
aws
aws_n = arr[arr<0]
aws_n

array([-1, -3, -5])

In [ ]:
arr_2d = np.array([[1,-2,-3,4],[2,-4,-5,6]])
index = [1,2,3]
arr[index]
a = arr_2d[arr_2d<0]
print(a)


[-2 -3 -4 -5]


In [ ]:
b = arr_2d[arr_2d>0]
print(b)


[1 4 2 6]


In [ ]:
arr_3d = np.array([[[1,2,3],[-2,-3,4],[-9,-4,6]]])
a = arr_3d[arr_3d<0]
print(a)

[-2 -3 -9 -4]


In [ ]:
b = arr_3d[arr_3d>0]
print(b)

[1 2 3 4 6]


In [ ]:
arr_4d = np.array([[[[1,2,3],[-2,-3,4],[-9,-4,6]]]])
a = arr_4d[arr_3d<0]
print(a)

[-2 -3 -9 -4]


In [ ]:
arr = np.array([1,2,3,4,5])
arr_col = arr[:,np.newaxis]
print(arr_col)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
arr = np.array([[1,2,3,4,5],[2,3,4,5,6]])
arr_col = arr[:,np.newaxis]
print(arr_col)

[[[1 2 3 4 5]]

 [[2 3 4 5 6]]]


In [ ]:
arr = np.array([[[1,2,3,4,5]]])
arr_col = arr[:,np.newaxis]
print(arr_col)

[[[[1 2 3 4 5]]]]


In [ ]:
arr = np.array([20,50,60])
arr_col=arr[:,np.newaxis]
c = arr_col-arr
print(c)


[[  0 -30 -40]
 [ 30   0 -10]
 [ 40  10   0]]


In [ ]:
dtype = [('name','S10'),('age','i4'),('weight','f4')]
arr = np.array([('deepika',25,26.0),('kiran',26,50.0)],dtype=dtype)
print(arr['name'])
print(arr['age'])
print(arr['weight'])

[b'deepika' b'kiran']
[25 26]
[26. 50.]
